# Generated by Django 4.0.6 on 2022-07-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('detalle', models.CharField(max_length=150)),
                ('stock', models.IntegerField(default='0')),
                ('stock_minimo', models.IntegerField(default='0')),
                ('ultima_compra', models.DateField(null=True)),
                ('observaciones', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
