# Generated by Django 4.0.6 on 2022-07-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20220727_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
