# Generated by Django 4.0.6 on 2022-07-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ultima_compra',
            field=models.DateTimeField(null=True),
        ),
    ]
