# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='detalle',
            field=models.CharField(max_length=150, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='observaciones',
            field=models.CharField(max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.IntegerField(default='0', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default='0', verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ultima_compra',
            field=models.DateTimeField(null=True, verbose_name='Ultima Compra'),
        ),
    ]
