# Generated by Django 4.0.6 on 2022-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_inventario_codigo_alter_inventario_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ultima_compra',
            field=models.DateField(null=True, verbose_name='Ultima Compra'),
        ),
    ]
