# Generated by Django 4.0.6 on 2022-07-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_inventario_ultima_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima Compra'),
        ),
    ]
