# Generated by Django 4.1 on 2022-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_delete_clientes_alter_inventario_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=100)),
                ('id_padre', models.IntegerField()),
            ],
        ),
    ]
