# Generated by Django 4.1 on 2022-08-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rubros'),
    ]

    operations = [
    ]
