# Generated by Django 4.1 on 2022-08-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20220831_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rubros',
        ),
    ]
