# Generated by Django 4.2.4 on 2023-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.IntegerField(verbose_name='Rubro')),
                ('subrubro', models.IntegerField(verbose_name='Sub-Rubro')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('detalle', models.CharField(max_length=255, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
                'db_table': 'inventario',
                'ordering': ['rubro', 'subrubro', 'codigo'],
                'managed': True,
            },
        ),
    ]
