# Generated by Django 4.1 on 2022-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Subrubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle')),
                ('id_rubro', models.IntegerField()),
            ],
        ),
    ]
