# Generated by Django 4.2.3 on 2023-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_provincia', models.IntegerField(verbose_name='Código Provincia')),
                ('codigo_localidad', models.IntegerField(verbose_name='Código Localidad')),
                ('nombre_localidad', models.CharField(max_length=100, verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Localidades',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['codigo_provincia', 'codigo_localidad', 'nombre_localidad'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincias',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['codigo', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rubro', models.IntegerField(verbose_name='Id Rubro')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
                ('id_rubro_padre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Rubros',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubros',
                'ordering': ['id_rubro', 'id_rubro_padre', 'detalle'],
                'managed': True,
            },
        ),
    ]
