# Generated by Django 4.0.6 on 2022-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_provincia', models.IntegerField(verbose_name='Código Provincia')),
                ('codigo_localidad', models.IntegerField(verbose_name='Código Localidad')),
                ('nombre_localidad', models.CharField(max_length=100, verbose_name='Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
        ),
    ]
