# Generated by Django 4.2.4 on 2023-08-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincias',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['codigo', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Rubro')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Rubros',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubros',
                'ordering': ['id', 'detalle'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subrubros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Sub-Rubro')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.rubros', verbose_name='Rubros')),
            ],
            options={
                'verbose_name': 'SubRubros',
                'verbose_name_plural': 'SubRubros',
                'db_table': 'subrubros',
                'ordering': ['id_rubro', 'id', 'detalle'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_localidad', models.IntegerField(verbose_name='Código Localidad')),
                ('nombre_localidad', models.CharField(max_length=100, verbose_name='Localidad')),
                ('codigo_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Localidades',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['codigo_provincia', 'codigo_localidad', 'nombre_localidad'],
                'managed': True,
            },
        ),
    ]
