# Generated by Django 4.0.6 on 2022-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rubro', models.IntegerField(verbose_name='Id Rubro')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
                ('id_rubro_padre', models.IntegerField()),
            ],
        ),
    ]
