# Generated by Django 4.0.6 on 2022-08-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rubros'),
    ]

    operations = [
    ]
