# Generated by Django 4.0.6 on 2022-08-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20220808_0707'),
    ]

    operations = [
    ]
