# Generated by Django 4.0.6 on 2022-07-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=15, verbose_name='CUIL/CUIT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('fecha_alta', models.DateField(auto_now=True, verbose_name='Fecha de Alta')),
                ('localidad', models.IntegerField(default=0, verbose_name='Localidad')),
                ('provincia', models.IntegerField(default=0, verbose_name='Provincia')),
                ('estado', models.CharField(default='A', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
