# Generated by Django 4.0.6 on 2022-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha de Alta'),
        ),
    ]
