# Generated by Django 4.1 on 2022-08-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_fecha_alta'),
    ]

    operations = [
    ]
