# Generated by Django 4.1 on 2022-08-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220809_1014'),
    ]

    operations = [
    ]
