# Generated by Django 4.1 on 2022-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit_cuil', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=100)),
                ('provincia', models.IntegerField()),
                ('localidad', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('observaciones', models.TextField(max_length=256)),
            ],
        ),
    ]
